# Generated by Django 4.0.5 on 2022-08-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0010_alter_well_name'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargeandcredit',
            options={'verbose_name': 'شارژ و اعتبار', 'verbose_name_plural': 'شارژ\u200cها و اعتبار\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='modifyname',
            options={'verbose_name': 'اصلاح نام', 'verbose_name_plural': 'اصلاح\u200cهای نام'},
        ),
        migrations.AlterModelOptions(
            name='technicalcondition',
            options={'verbose_name': 'وضعیت فنی', 'verbose_name_plural': 'وضعیت\u200cهای فنی'},
        ),
        migrations.AlterField(
            model_name='modifyname',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifyname', to='well.well', verbose_name='چاه متصل'),
        ),
    ]
