# Generated by Django 4.0.5 on 2022-08-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0010_alter_well_name'),
        ('license', '0002_alter_chargeandcredit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeandcredit',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChargeAndCredit', to='well.well', verbose_name='چاه متصل'),
        ),
        migrations.AlterField(
            model_name='modifyname',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifyname', to='well.well', verbose_name='چاه متصل'),
        ),
        migrations.AlterField(
            model_name='technicalcondition',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TechnicalCondition', to='well.well', verbose_name='چاه متصل'),
        ),
    ]
