# Generated by Django 4.0.5 on 2022-08-04 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0011_beneficiary'),
        ('license', '0004_alter_modifyname_well'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'verbose_name': 'تعهدنامه', 'verbose_name_plural': 'تعهدنامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='issuance',
            options={'verbose_name': 'وضعیت نهایی\u200cشارژ و صدور فرم', 'verbose_name_plural': 'وضعیت نهایی شارژ\u200cها و صدور فرم\u200cها'},
        ),
        migrations.AddField(
            model_name='commitment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 4, 8, 32, 30, 656761, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='جزییات بیشتر'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='مدارک'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'تایید\u200c شده'), ('n', 'بررسی نشده'), ('d', 'رد شده')], max_length=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commitment', to='well.well', verbose_name='چاه متصل'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='annual_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='شارژ سالیانه'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 4, 8, 32, 38, 306406, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuance',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='جزییات بیشتر'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='remaining_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='شارژ باقی مانده'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'تایید\u200c شده'), ('n', 'بررسی نشده'), ('d', 'رد شده')], max_length=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuance',
            name='used_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='شارژ مصرف\u200cشده'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Issuance', to='well.well', verbose_name='چاه متصل'),
        ),
    ]
