# Generated by Django 4.0.5 on 2022-07-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره پروانه')),
                ('license', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره پروانه')),
                ('licensePic', models.CharField(blank=True, max_length=200, null=True, verbose_name='عکس پروانه')),
                ('permitedAbdehi', models.CharField(blank=True, max_length=200, null=True, verbose_name='آبدهی مجاز')),
                ('permitedWorkTime', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعت کارکرد مجاز')),
                ('UTM', models.CharField(blank=True, max_length=200, null=True)),
                ('useType', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع بهرهبرداری')),
                ('permitedUseInYear', models.CharField(blank=True, max_length=200, null=True, verbose_name='اجازه\u200cی برداشت سالیانه')),
                ('chargeInYear', models.CharField(blank=True, max_length=200, null=True, verbose_name='شارژ فعلی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Well', to=settings.AUTH_USER_MODEL, verbose_name='مالک چاه')),
            ],
            options={
                'verbose_name': 'چاه',
                'verbose_name_plural': 'چاه\u200cها',
            },
        ),
    ]
