# Generated by Django 4.0.5 on 2022-07-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPhysicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmingType', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع کشت')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='مساحت')),
                ('depth', models.CharField(blank=True, max_length=200, null=True, verbose_name='عمق چاه')),
                ('power', models.CharField(blank=True, max_length=200, null=True, verbose_name='توان')),
                ('abdehi', models.CharField(blank=True, max_length=200, null=True, verbose_name='آبدهی')),
                ('pomp', models.CharField(blank=True, choices=[('k', 'شناور'), ('b', 'شفت و غلاف')], max_length=1, null=True, verbose_name='نوع پمپ')),
                ('buyCap', models.CharField(blank=True, max_length=200, null=True)),
                ('sellCap', models.CharField(blank=True, max_length=200, null=True)),
                ('wellCap', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Well', to='well.well', verbose_name='چاه متصل')),
            ],
            options={
                'verbose_name': 'ویژگی\u200cهای فیزیکی چاه',
                'verbose_name_plural': 'ویژگی\u200cهای فیزیکی چاه\u200cها',
            },
        ),
    ]
