# Generated by Django 4.0.5 on 2022-07-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0003_chahvand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chahvand',
            options={'verbose_name': 'حساب چاه\u200cوندی', 'verbose_name_plural': 'حساب\u200cهای چاه\u200cوندی'},
        ),
        migrations.CreateModel(
            name='AbVand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=200, verbose_name='شماره حساب')),
                ('currentcharge', models.CharField(blank=True, max_length=200, null=True, verbose_name='شارژ فعلی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AbVand', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'حساب آب\u200cوندی',
                'verbose_name_plural': 'حساب\u200cهای آب\u200cوندی',
            },
        ),
    ]
