# Generated by Django 4.0.5 on 2022-07-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0004_alter_chahvand_options_abvand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'حساب چاه', 'verbose_name_plural': 'حساب\u200cهای چاه\u200cها'},
        ),
    ]
