# Generated by Django 4.0.5 on 2022-07-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0005_alter_well_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abvand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='chahvand',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='چاه متصل'),
        ),
        migrations.AlterField(
            model_name='well',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک چاه'),
        ),
        migrations.AlterField(
            model_name='wellphysicalinfo',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='چاه متصل'),
        ),
        migrations.CreateModel(
            name='Chah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=200, verbose_name='شماره حساب')),
                ('currentcharge', models.CharField(blank=True, max_length=200, null=True, verbose_name='شارژ فعلی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='چاه متصل')),
            ],
            options={
                'verbose_name': 'حساب چاه\u200c',
                'verbose_name_plural': 'حساب\u200cهای چاه',
            },
        ),
    ]
