# Generated by Django 4.0.5 on 2022-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0006_alter_abvand_owner_alter_chahvand_well_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس'),
        ),
    ]
