# Generated by Django 4.0.5 on 2022-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0007_alter_well_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='useType',
            field=models.CharField(blank=True, choices=[('k', 'کشاورزی'), ('b', 'شرب'), ('b', 'صنعت')], max_length=1, null=True, verbose_name='نوع بهرهبرداری'),
        ),
    ]
