# Generated by Django 4.0.5 on 2022-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0008_alter_well_usetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'چاه', 'verbose_name_plural': 'چاه\u200cها'},
        ),
        migrations.AlterField(
            model_name='well',
            name='licensePic',
            field=models.FileField(blank=True, null=True, upload_to='licensePic', verbose_name='عکس پروانه'),
        ),
    ]
