# Generated by Django 4.0.5 on 2022-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0009_alter_well_options_alter_well_licensepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
