# Generated by Django 4.0.5 on 2022-08-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0011_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellphysicalinfo',
            name='well',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='چاه متصل'),
        ),
    ]
