# Generated by Django 4.0.5 on 2022-08-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0013_alter_wellphysicalinfo_well'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='idNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Beneficiary', to='well.well', verbose_name='چاه'),
        ),
    ]
