# Generated by Django 4.0.5 on 2022-08-05 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0014_remove_beneficiary_beneficiary_beneficiary_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2022, 8, 5, 14, 7, 22, 298229, tzinfo=utc), max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2022, 8, 5, 14, 7, 31, 597619, tzinfo=utc), max_length=200, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
