# Generated by Django 4.0.5 on 2022-07-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('well', '0006_alter_abvand_owner_alter_chahvand_well_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='حساب چاه')),
            ],
            options={
                'verbose_name': 'انتقال آب\u200cوندی به چاه\u200cوندی',
                'verbose_name_plural': 'انتقال\u200cهای آب\u200cوندی به چاه\u200cوندی',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('back', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction', verbose_name='برگشتی')),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.bucket', verbose_name='دلو')),
                ('from_abvand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.abvand', verbose_name='حساب آب\u200cوندی فرستنده')),
            ],
        ),
    ]
