# Generated by Django 4.0.5 on 2022-07-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0006_alter_abvand_owner_alter_chahvand_well_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_abvand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bb', to='well.abvand', verbose_name='حساب آب\u200cوندی گیرنده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_abvand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ff', to='well.abvand', verbose_name='حساب آب\u200cوندی فرستنده'),
        ),
    ]
