# Generated by Django 4.0.5 on 2022-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactiontype_alter_bucket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('aa', 'آب\u200cوندی به آب\u200cوندی'), ('ca', 'چاه\u200cوندی به آب\u200cوندی'), ('ac', 'آب\u200cوندی به چاه\u200cوندی'), ('cw', 'چاه\u200cوندی به چاه'), ('wc', 'چاه\u200c به چاه\u200cوندی')], max_length=2, null=True, verbose_name='نوع معامله'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
