# Generated by Django 4.0.5 on 2022-08-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0015_alter_beneficiary_firstname_and_more'),
        ('transaction', '0006_alter_transaction_from_abvand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی فعلی')),
                ('precredit', models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی قبلی')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('abvand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Credit', to='well.abvand', verbose_name='حساب آب\u200cوندی متصل')),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.bucket', verbose_name='دلو')),
                ('chahvand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Credit', to='well.chahvand', verbose_name='حساب چاه\u200cوندی متصل')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Credit', to='well.chah', verbose_name='حساب چاه متصل')),
            ],
            options={
                'verbose_name': 'مانده حساب',
                'verbose_name_plural': 'مانده حساب\u200cها',
            },
        ),
    ]
