# Generated by Django 4.0.5 on 2022-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_rename_date_transaction_created_transaction_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='precredit',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی قبلی'),
        ),
    ]
