# Generated by Django 4.0.5 on 2022-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contactus_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='ایمیل'),
        ),
    ]
