# Generated by Django 4.0.5 on 2022-07-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نقش')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_login.role', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='نام\u200cخانوادگی')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='شرکت')),
                ('fatherName', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پدر')),
                ('idNumber', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد ملی')),
                ('cardNumber', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره شناسنامه')),
                ('birthDate', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاریخ تولد')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('postCode', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد پستی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('confirmed', models.BooleanField(default=True, verbose_name='تایید حساب')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('pic', models.ImageField(blank=True, default='profileimages/profi.png', null=True, upload_to='profileimages', verbose_name='تصویر')),
                ('sphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
                ('status', models.BooleanField(default=True, verbose_name='حساب کاربری فعال؟')),
                ('role', models.ManyToManyField(blank=True, to='register_login.role', verbose_name='نقش')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب\u200cهای کاربری',
            },
        ),
    ]
