# Generated by Django 4.0.5 on 2022-07-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0010_alter_well_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('k', 'خرید'), ('f', 'فروش')], max_length=1, null=True, verbose_name='نوع معامله')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='مقدار معامله')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='مبلغ پیشنهادی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('expired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='well.well', verbose_name='چاه متصل')),
            ],
            options={
                'verbose_name': 'دادوستد',
                'verbose_name_plural': 'دادوستد\u200cها',
            },
        ),
    ]
