# Generated by Django 4.0.5 on 2022-07-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='expired',
            new_name='expire',
        ),
    ]
